// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxuxgaxbicffxdrugraq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4dXhnYXhiaWNmZnhkcnVncmFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzUzMTAsImV4cCI6MjA2NTA1MTMxMH0.mGC1fiL0nndNo8QpcZQS4kzLsO5GjvqlAunoOoVxeKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);